# Generated by Django 4.2.4 on 2024-02-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemanager_app', '0002_cinema_screening_cinema_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='cinema',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Cinema',
        ),
        migrations.DeleteModel(
            name='Screening',
        ),
    ]
